name_list = [
    'Lance',
    'Chara',
    'Henry',
     'Frisk',
  'YOUFOUNDTHESECRET',
  'Mettaton',
  '?_?',
    'JOJO',
    'Reginald',
    'Jimmie',
    'Leslie',
    'Loren',
    'Ivan',
    'Aurelio',
    'Heath',
    'Quincy',
    'Raymon',
   'Garrett',
    'Bryan',
    'Sebastian',
    'Gregory',
    'Jeffrey',
  'Jimmie',
    'Riley',
  'Preston',
    'Howard',
    'Dillon',
    'Johnnie',
    'Johnathon',
    'Shannon',
    'Lowell',
    'Jess',
    'Duane',
    'Kerry',
   'Reyes',
    'Douglas',
  'Tyson',
  'Roland',
  'Dee',
  'Scott',
  'Erich',
    'Jacob',
  'Randy',
  'Jackie_Clint',
  'Prince_Richard',
  'Hank',
  'Stephan',
  'Carey',
  'BufNed' ,
  'Johnnie',
  'Emilio',
  'Ralph',
  'Lenny',
'Dennis',
  'Nathaniel_B',
  'Colin_and_Miguel',
  'Ahmed',
  'Ahmet',
  'Undyne',
  'snans',
  'Hubert_Galeforce',
  'Lane_Omar_Marshall',
  'Roscoe',
  'Roosevelt',
  'Salvador',
  'Hank',
  'Israel',
'Louis_and_Lilia',
  'Kim',
  'Inez',
  'Jayne_Marion',
  'Lindsey_Minnie',
'Kristine_Ollie',
  'Jose_Katheryn',
  'Kathryn_is_ok_and',
'Dale',
'Nikki',
  'Tiffany',
  'Lillie',
 'Margie',
  'Alison',
  'Flowey',
  'jennifer'
]
title_list = [
'me_when',
'the_first',
'the_second',
"the_third",
'the_fourth',
'the_fifth',
'the_sixth',
'the_seventh',
'the_last'
]
spamton = [
  'MY EYES ARE [[Burning]] LIKE THE [[Television Sets at 50% the price]]',
  'WHY BE A [[Sponge]] THAT HATES ITS [[$4.99]] LIFE',
   'VACATIONING IN [Burning acid] WHILE YOU SOAK IN THE [[Hyperlink Blocked]]',
  'HERE I GO!!!! WATCH ME FLY, [MAMA]!!!!',
  'DONT FORGET TO [Like and Subscribe] FOR MORE [Hyperlink Blocked]!',
  'SPAMTON SWEEPSTAKES!!! DONATE TO CHARITY OR ENTER NOW TO [Win Pr13zes!] AND HELP OUT THE [Little Guys]',
  'THATS RIGHT!! NOWS YOUR CHANCE TO BE A [[BIG SHOT]]!!',
  'YOU WANT IT\nYOU WANT [[Hyperlink Blocked]], DONT YOU.',
  '[[A Great Deal]] IS WAITING For [[A LimiTed Time Only!]]\nA HEAVEN-PIERCING [[Workout-Ready Body]]',
  'EVERY [Big], EVERY [Shot], EVERY [Hyperlink Blocked], ALL YOURS, KRIS.',
  'TOO MANY EXCESS VACATION DAYS?? TAKE A GOD DAMN VACATION STRAIGHT TO HELL',
  'TURNING DOWN A BELOVED [[Stranger]]... THATS NOT VERY [[Big Shot]] OF YOU, KRIS.',
  'WHAT ARE YOU AFRAID OF??? ACCORDING TO [[Encyclopedia of]] [[Being Afraid]]',
  'can anyone hear me...help...',
  'WE DONT NEED ANY [[Man, Woman, or Child]] [[At Half Price]]!!'
]